### ISSUE TITLE
subtract with overflow issue

### ISSUE THREAD

**Issue by dubcdr** [dubcdr/mkr-listen#7]
```
New block 0x14ee…f64c
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/lib.rs:190:25
Txn 0xe661…3964 :: Swap 0.2 ETH for 0 0x2dccb4375d61f55a43ff3c611187284e50d85529
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: uni_listen::uni_v2::UniTxnInputs::parse_u256_to_f64
             at ./src/lib.rs:190:25
   4: uni_listen::uni_v2::UniTxnInputs::build_eth_str
             at ./src/lib.rs:178:25
   5: uni_listen::uni_v2::UniTxnInputs::build_side_str
             at ./src/lib.rs:172:11
   6: uni_listen::uni_v2::UniTxnInputs::log_str
             at ./src/lib.rs:149:24
   7: uni_listen::uni_v2::parallel_decode_uni_txns_call_data::{{closure}}
             at ./src/lib.rs:246:21
```

**Comment by dubcdr** [comment]
```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: uni_listen::uni_v2::UniTxnInputs::parse_u256_to_f64
             at ./src/lib.rs:190:25
   4: uni_listen::uni_v2::UniTxnInputs::build_eth_str
             at ./src/lib.rs:178:25
   5: uni_listen::uni_v2::UniTxnInputs::build_side_str
             at ./src/lib.rs:172:11
   6: uni_listen::uni_v2::UniTxnInputs::log_str
             at ./src/lib.rs:149:24
   7: uni_listen::uni_v2::parallel_decode_uni_txns_call_data::{{closure}}
             at ./src/lib.rs:246:21
```
